services:
  backend:
    build: ../backend
    volumes:
      - ../backend:/usr/scr/app
      - backend_node_modules:/usr/src/app/node_modules
    env_file:
      - .env.backend
    ports:
      - "8888:8888"
    command: sh -c "npm run setup && npm run dev"
    networks:
      - server-mongo
    depends_on:
      - mongo

  frontend:
    build: ../frontend
    volumes:
      - ../frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env.frontend
    depends_on:
      - backend
    
  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - server-mongo

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse

volumes:
  mongodb_data:
  backend_node_modules:
  frontend_node_modules:
  clickhouse-data:

networks:
  server-mongo: