services:
  backend:
    build: ../apps/backend
    volumes:
      - ../apps/backend:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    env_file:
      - .env.backend
    ports:
      - "8888:8888"
    command: sh -c "npm run dev"
    networks:
      - server-mongo
    depends_on:
      - mongo
      - grafana

  frontend:
    build: ../apps/frontend
    volumes:
      - ../apps/frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "pnpm run dev"
    env_file:
      - .env.frontend
    depends_on:
      - backend
    networks:
      - server-mongo
    
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - server-mongo

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse/config/:/etc/clickhouse-server/users.d/
    environment:
      - CLICKHOUSE_DB=default
    ulimits:
      nofile:
        soft: 262144 
        hard: 262144 

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "5000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - clickhouse

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - server-mongo

volumes:
  mongodb_data:
  backend_node_modules:
  frontend_node_modules:
  clickhouse-data:
  grafana_data:

networks:
  server-mongo: